baseUrl = "https://wgvanveen.com"
languageCode = "en"

title = "wgvanveen.com"

[params.author]
name = "Wouter van Veen"

headline = "A personal tech blog"


[caches]
	[caches.images]
		dir= ':cacheDir/images'


[services]
  [services.googleAnalytics]
    id = "G-4NN8YNW3V6"

