title = "Wouter's Techblog"

[params.author]
name = "Wouter van Veen"
headline = "Welcome to my techblog. I will mainly write about event-driven systems, Kubernetes, Quarkus, Kafka, Spring Boot and everything in between. Feel free to reach out if you have any questions ore suggestions!"
bio = "Senior backend engineer"
image = "profile.png"
links = [
  { github = "https://github.com/woutervanveen" },
  { email = "mailto:wgvanveen@wgvanveen.com" },
  { bluesky = "https://bsky.app/profile/wgvanveen.bsky.social" },
  { linkedin = "https://www.linkedin.com/in/wgvanveen/" }

]
